package com.rmd.personal.projecteuler;

import java.util.ArrayList;
import java.util.List;

public final class Common {

    private Common() {

    }

    private static List<Integer> primes;

    static {
        primes = new ArrayList<Integer>();
        populatePrimesList();
    }

    protected static int getNextPrime(int currentPrime) {
        return primes.get(primes.indexOf(currentPrime) + 1);
    }

    private static void populatePrimesList() { // SUPPRESS CHECKSTYLE methodLength
        primes.add(2); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(11); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(13); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(17); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(19); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(23); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(29); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(31); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(37); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(41); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(43); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(47); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(53); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(59); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(61); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(67); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(71); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(73); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(79); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(83); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(89); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(97); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(101); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(103); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(107); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(109); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(113); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(127); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(131); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(137); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(139); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(149); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(151); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(157); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(163); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(167); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(173); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(179); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(181); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(191); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(193); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(197); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(199); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(211); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(223); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(227); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(229); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(233); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(239); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(241); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(251); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(257); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(263); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(269); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(271); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(277); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(281); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(283); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(293); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(307); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(311); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(313); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(317); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(331); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(337); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(347); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(349); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(353); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(359); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(367); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(373); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(379); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(383); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(389); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(397); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(401); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(409); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(419); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(421); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(431); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(433); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(439); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(443); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(449); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(457); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(461); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(463); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(467); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(479); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(487); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(491); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(499); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(503); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(509); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(521); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(523); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(541); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(547); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(557); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(563); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(569); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(571); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(577); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(587); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(593); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(599); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(601); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(607); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(613); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(617); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(619); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(631); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(641); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(643); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(647); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(653); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(659); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(661); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(673); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(677); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(683); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(691); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(701); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(709); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(719); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(727); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(733); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(739); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(743); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(751); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(757); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(761); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(769); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(773); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(787); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(797); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(809); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(811); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(821); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(823); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(827); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(829); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(839); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(853); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(857); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(859); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(863); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(877); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(881); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(883); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(887); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(907); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(911); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(919); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(929); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(937); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(941); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(947); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(953); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(967); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(971); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(977); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(983); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(991); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(997); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1009); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1013); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1019); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1021); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1031); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1033); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1039); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1049); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1051); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1061); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1063); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1069); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1087); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1091); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1093); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1097); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1103); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1109); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1117); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1123); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1129); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1151); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1153); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1163); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1171); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1181); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1187); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1193); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1201); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1213); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1217); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1223); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1229); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1231); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1237); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1249); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1259); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1277); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1279); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1283); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1289); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1291); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1297); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1301); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1303); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1307); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1319); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1321); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1327); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1361); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1367); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1373); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1381); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1399); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1409); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1423); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1427); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1429); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1433); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1439); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1447); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1451); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1453); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1459); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1471); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1481); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1483); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1487); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1489); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1493); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1499); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1511); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1523); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1531); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1543); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1549); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1553); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1559); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1567); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1571); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1579); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1583); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1597); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1601); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1607); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1609); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1613); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1619); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1621); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1627); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1637); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1657); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1663); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1667); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1669); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1693); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1697); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1699); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1709); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1721); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1723); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1733); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1741); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1747); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1753); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1759); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1777); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1783); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1787); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1789); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1801); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1811); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1823); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1831); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1847); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1861); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1867); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1871); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1873); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1877); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1879); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1889); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1901); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1907); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1913); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1931); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1933); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1949); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1951); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1973); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1979); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1987); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1993); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1997); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(1999); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2003); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2011); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2017); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2027); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2029); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2039); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2053); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2063); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2069); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2081); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2083); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2087); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2089); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2099); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2111); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2113); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2129); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2131); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2137); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2141); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2143); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2153); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2161); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2179); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2203); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2207); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2213); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2221); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2237); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2239); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2243); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2251); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2267); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2269); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2273); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2281); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2287); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2293); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2297); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2309); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2311); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2333); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2339); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2341); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2347); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2351); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2357); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2371); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2377); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2381); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2383); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2389); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2393); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2399); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2411); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2417); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2423); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2437); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2441); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2447); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2459); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2467); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2473); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2477); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2503); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2521); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2531); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2539); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2543); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2549); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2551); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2557); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2579); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2591); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2593); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2609); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2617); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2621); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2633); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2647); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2657); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2659); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2663); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2671); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2677); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2683); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2687); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2689); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2693); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2699); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2707); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2711); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2713); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2719); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2729); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2731); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2741); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2749); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2753); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2767); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2777); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2789); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2791); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2797); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2801); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2803); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2819); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2833); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2837); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2843); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2851); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2857); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2861); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2879); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2887); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2897); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2903); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2909); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2917); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2927); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2939); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2953); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2957); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2963); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2969); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2971); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(2999); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3001); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3011); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3019); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3023); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3037); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3041); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3049); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3061); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3067); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3079); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3083); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3089); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3109); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3119); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3121); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3137); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3163); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3167); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3169); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3181); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3187); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3191); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3203); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3209); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3217); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3221); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3229); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3251); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3253); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3257); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3259); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3271); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3299); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3301); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3307); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3313); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3319); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3323); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3329); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3331); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3343); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3347); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3359); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3361); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3371); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3373); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3389); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3391); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3407); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3413); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3433); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3449); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3457); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3461); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3463); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3467); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3469); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3491); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3499); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3511); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3517); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3527); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3529); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3533); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3539); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3541); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3547); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3557); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3559); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3571); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3581); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3583); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3593); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3607); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3613); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3617); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3623); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3631); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3637); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3643); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3659); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3671); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3673); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3677); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3691); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3697); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3701); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3709); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3719); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3727); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3733); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3739); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3761); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3767); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3769); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3779); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3793); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3797); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3803); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3821); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3823); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3833); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3847); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3851); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3853); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3863); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3877); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3881); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3889); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3907); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3911); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3917); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3919); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3923); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3929); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3931); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3943); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3947); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3967); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(3989); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4001); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4003); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4007); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4013); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4019); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4021); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4027); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4049); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4051); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4057); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4073); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4079); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4091); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4093); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4099); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4111); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4127); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4129); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4133); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4139); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4153); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4157); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4159); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4177); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4201); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4211); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4217); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4219); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4229); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4231); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4241); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4243); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4253); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4259); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4261); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4271); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4273); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4283); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4289); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4297); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4327); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4337); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4339); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4349); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4357); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4363); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4373); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4391); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4397); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4409); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4421); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4423); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4441); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4447); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4451); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4457); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4463); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4481); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4483); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4493); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4507); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4513); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4517); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4519); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4523); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4547); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4549); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4561); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4567); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4583); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4591); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4597); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4603); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4621); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4637); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4639); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4643); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4649); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4651); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4657); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4663); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4673); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4679); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4691); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4703); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4721); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4723); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4729); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4733); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4751); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4759); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4783); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4787); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4789); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4793); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4799); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4801); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4813); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4817); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4831); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4861); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4871); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4877); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4889); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4903); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4909); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4919); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4931); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4933); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4937); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4943); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4951); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4957); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4967); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4969); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4973); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4987); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4993); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(4999); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5003); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5009); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5011); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5021); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5023); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5039); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5051); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5059); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5077); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5081); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5087); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5099); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5101); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5107); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5113); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5119); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5147); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5153); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5167); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5171); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5179); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5189); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5197); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5209); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5227); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5231); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5233); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5237); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5261); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5273); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5279); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5281); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5297); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5303); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5309); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5323); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5333); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5347); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5351); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5381); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5387); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5393); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5399); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5407); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5413); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5417); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5419); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5431); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5437); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5441); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5443); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5449); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5471); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5477); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5479); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5483); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5501); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5503); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5507); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5519); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5521); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5527); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5531); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5557); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5563); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5569); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5573); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5581); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5591); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5623); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5639); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5641); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5647); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5651); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5653); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5657); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5659); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5669); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5683); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5689); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5693); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5701); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5711); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5717); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5737); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5741); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5743); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5749); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5779); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5783); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5791); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5801); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5807); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5813); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5821); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5827); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5839); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5843); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5849); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5851); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5857); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5861); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5867); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5869); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5879); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5881); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5897); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5903); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5923); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5927); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5939); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5953); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5981); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(5987); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6007); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6011); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6029); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6037); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6043); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6047); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6053); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6067); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6073); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6079); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6089); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6091); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6101); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6113); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6121); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6131); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6133); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6143); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6151); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6163); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6173); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6197); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6199); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6203); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6211); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6217); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6221); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6229); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6247); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6257); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6263); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6269); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6271); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6277); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6287); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6299); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6301); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6311); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6317); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6323); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6329); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6337); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6343); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6353); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6359); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6361); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6367); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6373); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6379); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6389); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6397); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6421); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6427); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6449); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6451); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6469); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6473); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6481); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6491); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6521); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6529); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6547); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6551); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6553); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6563); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6569); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6571); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6577); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6581); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6599); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6607); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6619); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6637); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6653); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6659); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6661); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6673); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6679); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6689); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6691); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6701); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6703); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6709); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6719); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6733); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6737); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6761); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6763); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6779); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6781); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6791); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6793); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6803); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6823); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6827); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6829); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6833); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6841); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6857); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6863); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6869); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6871); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6883); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6899); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6907); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6911); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6917); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6947); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6949); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6959); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6961); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6967); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6971); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6977); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6983); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6991); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(6997); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7001); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7013); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7019); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7027); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7039); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7043); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7057); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7069); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7079); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7103); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7109); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7121); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7127); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7129); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7151); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7159); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7177); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7187); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7193); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7207); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7211); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7213); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7219); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7229); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7237); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7243); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7247); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7253); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7283); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7297); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7307); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7309); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7321); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7331); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7333); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7349); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7351); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7369); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7393); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7411); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7417); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7433); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7451); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7457); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7459); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7477); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7481); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7487); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7489); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7499); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7507); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7517); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7523); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7529); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7537); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7541); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7547); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7549); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7559); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7561); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7573); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7577); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7583); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7589); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7591); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7603); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7607); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7621); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7639); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7643); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7649); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7669); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7673); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7681); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7687); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7691); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7699); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7703); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7717); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7723); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7727); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7741); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7753); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7757); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7759); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7789); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7793); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7817); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7823); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7829); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7841); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7853); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7867); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7873); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7877); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7879); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7883); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7901); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7907); //SUPPRESS CHECKSTYLE magicNumber
        primes.add(7919); //SUPPRESS CHECKSTYLE magicNumber
    }

    protected static long sum(long n) {
        return (n * (n + 1)) / 2;
    }
}
