package com.rmd.personal.projecteuler;

public class P044 implements Problem {

    @Override
    public String getDescription() {
        return "Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers "
                + "are:\n\n"
                + "1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...\n\n"
                + "It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, "
                + "is not pentagonal.\n\n"
                + "Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal "
                + "and D = |Pk − Pj| is minimised; what is the value of D?";
    }

    @Override
    public String run() {
        long difference = -1;

        int n = 1;
        while (difference == -1) {
            long j = this.getTriangleNumberByIndex(n);
            for (int m = 1; m < n; m++) {
                long k = this.getTriangleNumberByIndex(m);
                if (Common.isPentagonal(j + k)
                        && Common.isPentagonal(j - k)) {
                    difference = j - k;
                }
            }
            n++;
        }

        return String.valueOf(difference);
    }

    private long getTriangleNumberByIndex(int n) {
        return n * ((3 * n) - 1) / 2;
    }
}
